/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author oro
 */
public class Jugar extends javax.swing.JFrame {

    /**
     * Creates new form Jugar
     */
    public Jugar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        txt_pregunta = new javax.swing.JLabel();
        Rbtn_Respuesta1 = new javax.swing.JRadioButton();
        Rbtn_Respuesta2 = new javax.swing.JRadioButton();
        Rbtn_Respuesta3 = new javax.swing.JRadioButton();
        Rbtn_Respuesta4 = new javax.swing.JRadioButton();
        Btn_Siguiente = new javax.swing.JButton();
        Btn_Salir = new javax.swing.JToggleButton();
        Lb_nombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Lb_puntaje = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Lb_Dificultad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_pregunta.setText("Pregunta");

        Rbtn_Respuesta1.setText("Respuesta 1");

        Rbtn_Respuesta2.setText("Respuesta 2");

        Rbtn_Respuesta3.setText("Respuesta 3");

        Rbtn_Respuesta4.setText("Respuesta 4");

        Btn_Siguiente.setText("Siguiente");

        Btn_Salir.setText("Salir");
        Btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalirActionPerformed(evt);
            }
        });

        Lb_nombre.setText("Nombre");

        jLabel1.setText("Puntaje:");

        jLabel2.setText("Nombre:");

        Lb_puntaje.setText("Puntaje");

        jLabel3.setText("Dificultad:");

        Lb_Dificultad.setText("Dificultad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Btn_Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Rbtn_Respuesta4)
                                    .addComponent(Rbtn_Respuesta3)
                                    .addComponent(Rbtn_Respuesta2)
                                    .addComponent(Rbtn_Respuesta1)
                                    .addComponent(txt_pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Lb_nombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lb_Dificultad)
                                .addGap(127, 127, 127)))
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Lb_puntaje)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Salir)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Salir)
                    .addComponent(Lb_nombre)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(Lb_puntaje)
                    .addComponent(jLabel3)
                    .addComponent(Lb_Dificultad))
                .addGap(18, 18, 18)
                .addComponent(txt_pregunta)
                .addGap(27, 27, 27)
                .addComponent(Rbtn_Respuesta1)
                .addGap(18, 18, 18)
                .addComponent(Rbtn_Respuesta2)
                .addGap(18, 18, 18)
                .addComponent(Rbtn_Respuesta3)
                .addGap(18, 18, 18)
                .addComponent(Rbtn_Respuesta4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(Btn_Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalirActionPerformed
        this.setVisible(false);
        Inicio i= new Inicio();
        i.setVisible(true);
    }//GEN-LAST:event_Btn_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jugar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Btn_Salir;
    private javax.swing.JButton Btn_Siguiente;
    private javax.swing.JLabel Lb_Dificultad;
    private javax.swing.JLabel Lb_nombre;
    private javax.swing.JLabel Lb_puntaje;
    private javax.swing.JRadioButton Rbtn_Respuesta1;
    private javax.swing.JRadioButton Rbtn_Respuesta2;
    private javax.swing.JRadioButton Rbtn_Respuesta3;
    private javax.swing.JRadioButton Rbtn_Respuesta4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txt_pregunta;
    // End of variables declaration//GEN-END:variables
}
